name: deployment
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Checkout this repository
      uses: actions/checkout@v2
    - name: Build the static site
      run: nix-build site/ --attr html.all
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./result
    - name: Cache the result to S3 (Backblaze B2)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.B2_APPKEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.B2_APPKEY }}
      run: |
        nix copy --to \
          's3://noteed-actions/cache?endpoint=s3.eu-central-003.backblazeb2.com' \
          ./result
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Backblaze B2 command-line tool
      run: |
        python -m pip install --upgrade pip
        pip install --quiet --no-cache-dir b2==2.0.2
    - name: Sync to Backblaze B2
      run: |
        b2 authorize-account ${{ secrets.B2_APPKEY_ID }} ${{ secrets.B2_APPKEY }}
        b2 sync --delete --replaceNewer ./result/ b2://noteed-actions/site/
        b2 clear-account
